#!/tmp/bootimgtools/tools/bash
tooldir=/tmp/bootimgtools/tools
box=$tooldir/busybox
# copy insecure adb from twrp to ramdisk
$box cp /sbin/adbd $tooldir/kernel/ramdisk/sbin
cd $tooldir/kernel/ramdisk
$box sed -i -f $tooldir/../install/replace_defaultprop.sed default.prop