#!/tmp/bootimgtools/tools/bash
tooldir=/tmp/bootimgtools/tools
box=$tooldir/busybox
# copy insecure adb from twrp to ramdisk
$box cp /sbin/adbd $tooldir/patimg/ramdisk/sbin
cd $tooldir/patimg/ramdisk
$busybox sed -i -f $tooldir/../install/replace_defaultprop.sed default.prop