#!/tmp/bootimgtools/tools/bash
tooldir=/tmp/bootimgtools/tools
box=$tooldir/busybox
cd $tooldir/patimg/ramdisk
$box rm *.ranchu* *.goldfish* init.container.rc sbin/knox_changer

# fix a bug
cd $tooldir/patimg/ramdisk/sbin
$box rm ueventd watchdogd
ln -s ../init ueventd
ln -s ../init watchdogd
