#!/tmp/bootimgtools/tools/bash
tooldir=/tmp/bootimgtools/tools
box=$tooldir/busybox
cd $tooldir/patimg/ramdisk

# remove insecure adb stuff
$box sed -i -f $tooldir/../uninstall/replace_defaultprop_remove.sed default.prop

# remove busybox
$box rm sbin/busybox

# remove permissive (old version) 
$box rm /system/etc/init.d/00permkernel
#new version
$box rm init.permissive.rc
$box sed -i '\|import /init.permissive.rc|d' init.rc

#remove init.d support (if old version) 
$box rm sbin/sysinit
$box cat init.rc > init.rc2
$box sleep 1s
$box awk '/# init.d support/{p=1;print "service flash_recovery /system/bin/install-recovery.sh\n    class main"}/oneshot/{p=0}!p' init.rc2 > init.rc
# fix a bug/let the system catch up
$box sleep 1s
$box rm init.rc2
#new version remove
$box rm init.initd.rc
$box sed -i '\|import /init.initd.rc|d' init.rc

# remove root
$box sed -i -f $tooldir/../uninstall/replace_file_contexts.sed file_contexts
$box sed -i -f $tooldir/../uninstall/replace_initenvironrc.sed init.environ.rc
$box sed -i -f $tooldir/../uninstall/replace_initrc.sed init.rc
$box rm -rf .subackup/
$box rm -rf su/
$box rm sbin/launch_daemonsu.sh
$box rm init.supersu.rc
$box rm /data/su.img
$box rm /data/stock_boot_*.gz
# the * should fix a root bug people are still having
$box rm -rf /data/app/eu.chainfire.supersu*
$box rm /data/dalvik-cache/profiles/eu.chainfire.supersu
$box rm -rf /data/data/eu.chainfire.supersu
